import type { Config } from "tailwindcss";

// Design tokens lifted verbatim from the "Elite Operation" design system
// (see design/DESIGN.md) so every screen in the app matches the approved mock.
const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d8dadd",
        "on-surface": "#191c1e",
        "on-tertiary-fixed": "#001f27",
        "on-surface-variant": "#464555",
        "on-tertiary-fixed-variant": "#004e5f",
        "primary-container": "#635bff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "on-secondary-container": "#5c617c",
        "on-tertiary": "#ffffff",
        "secondary-container": "#dadefd",
        "primary-fixed-dim": "#c3c0ff",
        "secondary-fixed-dim": "#c1c5e3",
        "outline-variant": "#c7c4d8",
        "surface-container": "#eceef1",
        "surface-container-highest": "#e0e3e6",
        "surface-variant": "#e0e3e6",
        "surface-container-high": "#e6e8eb",
        "error-container": "#ffdad6",
        "on-primary-container": "#fefaff",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "primary-fixed": "#e2dfff",
        "on-secondary-fixed-variant": "#41455f",
        secondary: "#585d77",
        "on-secondary-fixed": "#151a31",
        "inverse-surface": "#2d3133",
        primary: "#493ee5",
        "tertiary-fixed": "#b4ebff",
        "surface-bright": "#f7f9fc",
        "inverse-primary": "#c3c0ff",
        "on-background": "#191c1e",
        background: "#f7f9fc",
        "on-primary-fixed-variant": "#321ed2",
        tertiary: "#00647a",
        "tertiary-container": "#007f9a",
        "surface-container-low": "#f2f4f7",
        "on-error": "#ffffff",
        "on-tertiary-container": "#f8fdff",
        outline: "#777587",
        "secondary-fixed": "#dde1ff",
        "surface-container-lowest": "#ffffff",
        surface: "#f7f9fc",
        "surface-tint": "#4c42e9",
        "tertiary-fixed-dim": "#3cd7ff",
        "inverse-on-surface": "#eff1f4",
        // Semantic revenue-split tokens (see DESIGN.md "Revenue Split Indicators")
        "revenue-business": "#493ee5",
        "revenue-soap": "#00647a",
        "revenue-staff": "#585d77",
        success: "#10B981",
        warning: "#F59E0B",
        info: "#3B82F6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "32px",
        "stack-md": "16px",
        "sidebar-width": "260px",
        gutter: "24px",
        "card-padding": "24px",
        "container-max": "1440px",
        "stack-sm": "8px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-md-mobile": ["var(--font-inter)", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "display-lg": ["var(--font-inter)", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "body-lg": ["var(--font-inter)", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "label-caps": ["var(--font-inter)", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "headline-md": ["var(--font-inter)", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "data-tabular": ["var(--font-inter)", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "body-md": ["var(--font-inter)", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        sans: ["var(--font-inter)", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ["var(--font-inter)", "system-ui", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
      },
      fontSize: {
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "data-tabular": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      boxShadow: {
        "level-1": "0 4px 20px rgba(0, 0, 0, 0.04)",
        "level-2": "0 12px 32px rgba(0, 31, 39, 0.08)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
